### ISSUE TITLE
Bug in use_cache?

### ISSUE THREAD

**Issue by yanshuotan** [Yu-Group/simChef#131] opened 2022-12-18 13:45 UTC
After running an experiment:

`results <- run_experiment(experiment, n_reps = 10, save = T)`

I tried to use the cache to rerun it, but got an error

`> run_experiment(experiment, n_reps = 10, use_cached = T)`
`Error in if (n_reps_cached > 0) { : missing value where TRUE/FALSE needed`

Existing file structure [attached.](url)
![Screen Shot 2022-12-18 at 9 44 21 PM](https://user-images.githubusercontent.com/38105823/208301709-bb8b673c-98d7-4af3-8a0c-cea27aba44f3.png)

**Comment by tiffanymtang** [comment] 2022-12-19 15:42
Do you have the code snippet for creating the experiment?

**Comment by jpdunc23** [comment] 2022-12-19 17:44
Thanks for using `simChef`, @yanshuotan! Echoing @tiffanymtang, a small example to reproduce the error would be helpful. If you use a larger value for `n_reps` the second time around, e.g. `run_experiment(experiment, n_reps = 12, use_cached = T)`, does the error still occur?

On first glance, it looks like we need to wrap `n_reps_cached > 0` with `isTRUE()` or something similar.

**Comment by tiffanymtang** [comment] 2022-12-21 02:59
Got the code from @yanshuotan and wasn't able to recreate the error. Seems like caching is working so going to close this issue for now.

**Closed by tiffanymtang** 2022-12-21 02:59 UTC
Labels: bug
